# -*- coding: utf-8 -*-
"""homework0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m_FWuSx62wnYRov3Hv6Bjjw4d5aiQDM_

CSCI 158 **HOMEWORK 0**

In this homework assignment we explore the Numpy python package. For a brief introduction, go [here](https://numpy.org/devdocs/user/absolute_beginners.html).

Begin by importing the Numpy library:
"""

import numpy as np

"""Create a numpy array called `X` with 100 rows and 10 columns, where each entry is the number 1."""

X=np.array([[1]*10]*100)

"""Create a 1-dimensional numpy array called `y`, where the entries are the numbers 1 through 1000 (in order)."""

y=np.array(np.arange(1000)+1)

"""Create a numpy array called `Y` with 100 rows and 10 columns, whose entries come from the array `y`."""

Y=y.reshape(100,10)
Y

"""Use the np.newaxis command to create an array called `z`, with enties from `y`, which has 1000 rows and one column."""

z=y[:, np.newaxis]

"""Create an array of shape (5,4) called `A`, consisting of those entries in `Y` in the first 5 rows and columns 2-5.  """

A=Y[:5,2:6]

"""Create a 1-dimensional array called `b` consisting of the entries in `Y` that are divisible by 3, and between 20 and 70.

"""

multiples=Y.reshape(1,1000)[0,2::3]
b=multiples[multiples<70][multiples[multiples<70]>20]
b

"""Create an array called `Z` whose entries are the square-root of the entries in `Y`, plus the corresponding entries in `X`."""

Z=np.sqrt(Y) + X

"""Create a 1-D array `m` whose entries are the maximum of each column of `Y`."""

m=np.max(Y,axis=0)
m

"""Create a 1-D array `s` whose entries are the sums of each row of `Y`."""

s=Y.sum(axis=1)
s

"""Create an array `P` which is the product of `X` and the transpose of `Y`."""

P=np.matmul(X,Y.transpose())
P